method: bayes
metric:
  goal: minimize
  name: loss
parameters: 
  gamma: 
    distribution: categorical
    values: [0.9, 0.95, 0.98, 0.99, 0.995, 0.999, 0.9999]
  learning_rate: 
    distribution: log_uniform
    max: 1
    min: 0.00001
  batch_size:
    distribution: categorical
    values: [16, 32, 64, 100, 128, 256, 512]
  buffer_size: 
    distribution: categorical
    values: [10000, 50000, 80000]
  exploration_fraction:
    distribution: uniform
    min: 0
    max: 0.5
  exploration_final_eps:
    distribution: uniform
    min: 0
    max: 0.2
  target_update_interval: 
    distribution: categorical
    values: [1, 1000, 5000, 10000, 15000, 20000]
  learning_starts:
    distribution: categorical
    values: [0, 1000, 5000, 10000, 20000,50000]
  train_freq:
    distribution: categorical
    values: [1, 4, 8, 16, 128, 256, 1000]
command:
- ${env}
- .\venv\Scripts\python.exe
- ArcadeGame\train.py
- ${args}